Repository Dev5ps/market-karly, pull requests merged in 2023-02, with the labels that each got.

#40 main 페이지 카테고리 드롭다운의 z-index가 뒤로 밀리는 문제 및 배경색이 들어가 있지 않는 문제 해결
  client/css/main.css
  client/sass/layout/_navigation.scss
Labels: feat

#45 [setting] 이슈 템플릿 추가 #44
  .github/ISSUE_TEMPLATE/bug-fix-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: setting

#48 [chore] sprite 아이콘 assets 추가
  client/assets/sprite-icon/sprite-icons.png
Labels: chore

#101 [feat] 최근본상품 localstroage 등록 및 DOM에 추가
  client/cart.html
  client/css/main.css
  client/index.html
  client/js/index.js
  client/js/main.js
  client/js/main/index.js
  client/js/main/main-product-list-item.js
  client/js/main/recently-item.js
  client/js/main/recently-swiper.js
  client/js/main/recently-viewed.js
  client/js/poduct-detail/index.js
  client/js/product-detail/index.js
  client/js/product-detail/product-detail.js
  client/js/product-list/product-list-item.js
  client/js/product-list/product-list.js
  client/login.html
  client/product-akqk.html
  client/product-ckzk.html
  client/product-ekfk.html
  client/product-list.html
  client/product-rksk.html
  client/product-tkwk.html
  client/register.html
  client/sass/layout/_recently.scss
  client/sass/main.scss
Labels: feat

#117 [fix] 버그 수정 및 리팩토링 #116
  client/css/main.css
  client/js/common/main-banner.js
  client/js/main.js
  client/js/main/recently-swiper.js
  client/js/popup/popup.js
  client/sass/pages/_product-list.scss
Labels: fix

#119 [chore & fix] 전체적인 오류 수정 및 레이아웃 수정
  client/assets/main-banner/banner02.jpg
  client/assets/main-banner/banner03.jpg
  client/cart.html
  client/css/main.css
  client/index.html
  client/js/cart/add-to-cart.js
  client/js/common/index.js
  client/js/index.js
  client/js/main.js
  client/js/main/index.js
  client/js/main/main-banner-slide.js
  client/js/main/main-banner.js
  client/js/main/recently-item.js
  client/js/main/recently-swiper.js
  client/js/main/recently-viewed.js
  client/js/product-detail/product-detail.js
  client/login.html
  client/product-akqk.html
  client/product-ckzk.html
  client/product-ekfk.html
  client/product-list.html
  client/product-review.html
  client/product-rksk.html
  client/product-tkwk.html
  client/register.html
  client/sass/layout/_navigation.scss
  client/sass/pages/_register.scss
  server/db/data.json
Labels: feat, fix, chore

#121 [setting] README 파일 추가
  README.md
Labels: setting

#122 [chore] 오류 수정
  client/js/index.js
  client/js/main.js
  client/js/popup/index.js
  client/js/product-detail/index.js
  client/js/product-detail/popup.js
Labels: fix, chore
